name: ♻️ Auto Generate Snake Animation

on:
  schedule:
    - cron: "0 */2 * * *" 
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Generate contribution snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            profile/github-contribution-grid-snake.svg
            profile/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add profile/
          git commit -m "🐍 Update snake animation" || exit 0
          git push
